name: Build and Deploy ASP.NET 4.8 Application

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: windows-latest  # ASP.NET 4.8 requires Windows environment

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # Restore NuGet packages
      - name: Restore NuGet packages
        run: nuget restore ASPDotNetSampleWebapp.sln

      # Build the solution with detailed logging
      - name: Build the solution
        run: msbuild ASPDotNetSampleWebapp.sln /p:Configuration=Release /p:OutputPath="bin\Release" /v:detailed

      # List all files in workspace to debug output location
      - name: List all files in workspace
        run: |
          echo "Listing all files in workspace for debugging:"
          dir /s /b

      # Check if the output directory exists
      - name: Check Output Directory
        shell: pwsh
        run: |
          $workspace = "${{ github.workspace }}"
          $outputDir = Join-Path -Path $workspace -ChildPath "ASPDotNetSampleWebapp/bin/Release"
          if (Test-Path $outputDir) {
              Write-Output "Output directory exists: $outputDir"
              Get-ChildItem $outputDir
          } else {
              Write-Output "Output directory does not exist: $outputDir"
              exit 1
          }
