name: Build and Deploy ASP.NET 4.8 Application

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: windows-latest  # ASP.NET 4.8 requires Windows environment

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # Restore NuGet packages
      - name: Restore NuGet packages
        run: nuget restore ASPDotNetSampleWebapp.sln

      # Build the solution with detailed logging
      - name: Build the solution
        run: msbuild ASPDotNetSampleWebapp.sln /p:Configuration=Release /v:detailed

      #Check if the output directory exists
      - name: Check Output Directory
        run: |
          $outputDir = "D:\a\DotNet\DotNet\ASPDotNetSampleWebapp\bin\Release"
          if (Test-Path $outputDir) {
              echo "Output directory exists: $outputDir"
              Get-ChildItem $outputDir
          } else {
              echo "Output directory does not exist: $outputDir"
              exit 1
          }
